"""add 2 cols for terms and permissions

Revision ID: 623e37774ab3
Revises: 513787d9369d
Create Date: 2026-03-24 13:21:49.150115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '623e37774ab3'
down_revision: Union[str, Sequence[str], None] = '513787d9369d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('terms_agreed', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('improve_sentra_opt_in', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'improve_sentra_opt_in')
    op.drop_column('users', 'terms_agreed')
    # ### end Alembic commands ###
