"""Add feedback model

Revision ID: e3d15040c602
Revises: e6f7a8b9c0d1
Create Date: 2026-04-08 10:25:23.842026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3d15040c602'
down_revision: Union[str, Sequence[str], None] = 'e6f7a8b9c0d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_user_id'), 'feedback', ['user_id'], unique=False)
    op.drop_constraint(op.f('email_verifications_token_key'), 'email_verifications', type_='unique')
    op.drop_index(op.f('ix_email_verifications_token'), table_name='email_verifications')
    op.create_index(op.f('ix_email_verifications_token'), 'email_verifications', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_verifications_token'), table_name='email_verifications')
    op.create_index(op.f('ix_email_verifications_token'), 'email_verifications', ['token'], unique=False)
    op.create_unique_constraint(op.f('email_verifications_token_key'), 'email_verifications', ['token'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_feedback_user_id'), table_name='feedback')
    op.drop_table('feedback')
    # ### end Alembic commands ###
